### ISSUE TITLE
Suggestion: use "dygraphs" package for interactive time series visualization

### ISSUE THREAD

**Issue by rishabhshah-92** [tianshu129/foqat#66]
Having personally used the "dygraphs" package, I can confirm that it is really useful for interacting with time series data (i.e., zooming in and out), hovering mouse of specific data points to look at values, etc.

The package can be found here: https://rstudio.github.io/dygraphs/
The "xts" package may be required to prepare a dataframe as an input to dygraphs.

Happy to help out, debug, etc.
Rishabh

**Comment by tianshu129** [comment]
Hi Rishabh,

Thank you very much. I'm considering for some interacting with time series. You provide me a good insight. 
And thank you for your willing to help!

Best,

Tianshu
